import os
from PIL import Image

# Configuration
INPUT_DIR = "."  # Scans current directory and subfolders
OUTPUT_SHEET_NAME = "MasterSheet.png"
OUTPUT_LUA_NAME = "SpriteData.lua"
MAX_WIDTH = 1024
MAX_HEIGHT = 1024
PADDING = 0  # Zero gaps; images sit directly edge-to-edge

def pack_sprites():
    images_data = []
    
    print("Scanning folders for PNG textures...")
    for root, dirs, files in os.walk(INPUT_DIR):
        for file in files:
            if file.lower().endswith(".png"):
                if file == OUTPUT_SHEET_NAME or file == OUTPUT_LUA_NAME:
                    continue
                    
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, INPUT_DIR)
                
                # Creates a clean key like "basic/white" or "smileys/smiley_1"
                key = os.path.splitext(rel_path)[0].replace("\\", "/")
                
                try:
                    img = Image.open(full_path)
                    images_data.append({
                        "key": key,
                        "path": full_path,
                        "img": img,
                        "width": img.width,
                        "height": img.height
                    })
                except Exception as e:
                    print(f"Error loading {full_path}: {e}")

    if not images_data:
        print("No PNG files found to pack!")
        return

    # Sort by height descending for optimal packing
    images_data.sort(key=lambda x: x["height"], reverse=True)

    master_sheet = Image.new("RGBA", (MAX_WIDTH, MAX_HEIGHT), (0, 0, 0, 0))
    
    current_x = 0
    current_y = 0
    row_height = 0
    sprite_metadata = {}

    print("Packing textures tightly onto the 1024x1024 master sheet...")
    for item in images_data:
        w, h = item["width"], item["height"]
        
        # Wrap to next row if it exceeds max width
        if current_x + w > MAX_WIDTH:
            current_x = 0
            current_y += row_height
            row_height = 0
            
        if current_y + h > MAX_HEIGHT:
            print(f"ERROR: Asset '{item['key']}' exceeds the 1024x1024 canvas limit!")
            continue
            
        # Paste directly edge-to-edge
        master_sheet.paste(item["img"], (current_x, current_y))
        
        sprite_metadata[item["key"]] = {
            "offset_x": current_x,
            "offset_y": current_y,
            "width": w,
            "height": h
        }
        
        if h > row_height:
            row_height = h
            
        current_x += w

    master_sheet.save(OUTPUT_SHEET_NAME)
    print(f"Successfully generated master sheet: {OUTPUT_SHEET_NAME}")
    generate_lua_module(sprite_metadata, OUTPUT_LUA_NAME)

def generate_lua_module(metadata, lua_filename):
    lua_code = "-- Auto-generated by packer.py. Do not edit manually.\n\n"
    lua_code += "local SpriteData = {\n"
    lua_code += "    MasterSheetId = \"rbxassetid://YOUR_ASSET_ID_HERE\",\n"
    lua_code += "    Data = {\n"
    
    for key, data in metadata.items():
        lua_code += f"        [\"{key}\"] = {{\n"
        lua_code += f"            Offset = Vector2.new({data['offset_x']}, {data['offset_y']}),\n"
        lua_code += f"            Size = Vector2.new({data['width']}, {data['height']})\n"
        lua_code += f"        }},\n"
        
    lua_code += "    }\n"
    lua_code += "}\n\n"
    lua_code += "return SpriteData\n"
    
    with open(lua_filename, "w", encoding="utf-8") as f:
        f.write(lua_code)
    print(f"Successfully generated Lua metadata map: {lua_filename}")

if __name__ == "__main__":
    pack_sprites()
