-- Auto-generated by packer.py. Do not edit manually.

local SpriteData = {
    MasterSheetId = "rbxassetid://YOUR_ASSET_ID_HERE",
    Data = {
        ["smileys/79"] = {
            Offset = Vector2.new(0, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/82"] = {
            Offset = Vector2.new(26, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/124"] = {
            Offset = Vector2.new(52, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/10"] = {
            Offset = Vector2.new(78, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/144"] = {
            Offset = Vector2.new(104, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/119"] = {
            Offset = Vector2.new(130, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/39"] = {
            Offset = Vector2.new(156, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/86"] = {
            Offset = Vector2.new(182, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/22"] = {
            Offset = Vector2.new(208, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/126"] = {
            Offset = Vector2.new(234, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/163"] = {
            Offset = Vector2.new(260, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/101"] = {
            Offset = Vector2.new(286, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/81"] = {
            Offset = Vector2.new(312, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/34"] = {
            Offset = Vector2.new(338, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/96"] = {
            Offset = Vector2.new(364, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/94"] = {
            Offset = Vector2.new(390, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/87"] = {
            Offset = Vector2.new(416, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/52"] = {
            Offset = Vector2.new(442, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/130"] = {
            Offset = Vector2.new(468, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/70"] = {
            Offset = Vector2.new(494, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/166"] = {
            Offset = Vector2.new(520, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/18"] = {
            Offset = Vector2.new(546, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/128"] = {
            Offset = Vector2.new(572, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/97"] = {
            Offset = Vector2.new(598, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/159"] = {
            Offset = Vector2.new(624, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/14"] = {
            Offset = Vector2.new(650, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/60"] = {
            Offset = Vector2.new(676, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/181"] = {
            Offset = Vector2.new(702, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/104"] = {
            Offset = Vector2.new(728, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/19"] = {
            Offset = Vector2.new(754, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/147"] = {
            Offset = Vector2.new(780, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/120"] = {
            Offset = Vector2.new(806, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/33"] = {
            Offset = Vector2.new(832, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/46"] = {
            Offset = Vector2.new(858, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/175"] = {
            Offset = Vector2.new(884, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/31"] = {
            Offset = Vector2.new(910, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/37"] = {
            Offset = Vector2.new(936, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/58"] = {
            Offset = Vector2.new(962, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/68"] = {
            Offset = Vector2.new(988, 0),
            Size = Vector2.new(26, 26)
        },
        ["smileys/98"] = {
            Offset = Vector2.new(0, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/72"] = {
            Offset = Vector2.new(26, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/75"] = {
            Offset = Vector2.new(52, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/43"] = {
            Offset = Vector2.new(78, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/100"] = {
            Offset = Vector2.new(104, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/186"] = {
            Offset = Vector2.new(130, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/84"] = {
            Offset = Vector2.new(156, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/171"] = {
            Offset = Vector2.new(182, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/47"] = {
            Offset = Vector2.new(208, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/15"] = {
            Offset = Vector2.new(234, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/74"] = {
            Offset = Vector2.new(260, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/169"] = {
            Offset = Vector2.new(286, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/183"] = {
            Offset = Vector2.new(312, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/64"] = {
            Offset = Vector2.new(338, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/111"] = {
            Offset = Vector2.new(364, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/90"] = {
            Offset = Vector2.new(390, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/182"] = {
            Offset = Vector2.new(416, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/56"] = {
            Offset = Vector2.new(442, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/162"] = {
            Offset = Vector2.new(468, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/28"] = {
            Offset = Vector2.new(494, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/13"] = {
            Offset = Vector2.new(520, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/11"] = {
            Offset = Vector2.new(546, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/76"] = {
            Offset = Vector2.new(572, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/177"] = {
            Offset = Vector2.new(598, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/143"] = {
            Offset = Vector2.new(624, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/91"] = {
            Offset = Vector2.new(650, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/92"] = {
            Offset = Vector2.new(676, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/27"] = {
            Offset = Vector2.new(702, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/57"] = {
            Offset = Vector2.new(728, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/140"] = {
            Offset = Vector2.new(754, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/138"] = {
            Offset = Vector2.new(780, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/164"] = {
            Offset = Vector2.new(806, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/69"] = {
            Offset = Vector2.new(832, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/115"] = {
            Offset = Vector2.new(858, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/3"] = {
            Offset = Vector2.new(884, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/44"] = {
            Offset = Vector2.new(910, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/63"] = {
            Offset = Vector2.new(936, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/132"] = {
            Offset = Vector2.new(962, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/6"] = {
            Offset = Vector2.new(988, 26),
            Size = Vector2.new(26, 26)
        },
        ["smileys/54"] = {
            Offset = Vector2.new(0, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/157"] = {
            Offset = Vector2.new(26, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/145"] = {
            Offset = Vector2.new(52, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/141"] = {
            Offset = Vector2.new(78, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/5"] = {
            Offset = Vector2.new(104, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/156"] = {
            Offset = Vector2.new(130, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/17"] = {
            Offset = Vector2.new(156, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/105"] = {
            Offset = Vector2.new(182, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/53"] = {
            Offset = Vector2.new(208, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/38"] = {
            Offset = Vector2.new(234, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/21"] = {
            Offset = Vector2.new(260, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/161"] = {
            Offset = Vector2.new(286, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/148"] = {
            Offset = Vector2.new(312, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/154"] = {
            Offset = Vector2.new(338, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/32"] = {
            Offset = Vector2.new(364, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/173"] = {
            Offset = Vector2.new(390, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/110"] = {
            Offset = Vector2.new(416, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/107"] = {
            Offset = Vector2.new(442, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/103"] = {
            Offset = Vector2.new(468, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/26"] = {
            Offset = Vector2.new(494, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/62"] = {
            Offset = Vector2.new(520, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/168"] = {
            Offset = Vector2.new(546, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/129"] = {
            Offset = Vector2.new(572, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/80"] = {
            Offset = Vector2.new(598, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/85"] = {
            Offset = Vector2.new(624, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/180"] = {
            Offset = Vector2.new(650, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/25"] = {
            Offset = Vector2.new(676, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/133"] = {
            Offset = Vector2.new(702, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/83"] = {
            Offset = Vector2.new(728, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/187"] = {
            Offset = Vector2.new(754, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/149"] = {
            Offset = Vector2.new(780, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/88"] = {
            Offset = Vector2.new(806, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/78"] = {
            Offset = Vector2.new(832, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/113"] = {
            Offset = Vector2.new(858, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/136"] = {
            Offset = Vector2.new(884, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/139"] = {
            Offset = Vector2.new(910, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/109"] = {
            Offset = Vector2.new(936, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/66"] = {
            Offset = Vector2.new(962, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/152"] = {
            Offset = Vector2.new(988, 52),
            Size = Vector2.new(26, 26)
        },
        ["smileys/134"] = {
            Offset = Vector2.new(0, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/29"] = {
            Offset = Vector2.new(26, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/172"] = {
            Offset = Vector2.new(52, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/165"] = {
            Offset = Vector2.new(78, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/12"] = {
            Offset = Vector2.new(104, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/8"] = {
            Offset = Vector2.new(130, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/59"] = {
            Offset = Vector2.new(156, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/167"] = {
            Offset = Vector2.new(182, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/122"] = {
            Offset = Vector2.new(208, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/2"] = {
            Offset = Vector2.new(234, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/121"] = {
            Offset = Vector2.new(260, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/24"] = {
            Offset = Vector2.new(286, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/116"] = {
            Offset = Vector2.new(312, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/123"] = {
            Offset = Vector2.new(338, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/106"] = {
            Offset = Vector2.new(364, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/67"] = {
            Offset = Vector2.new(390, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/125"] = {
            Offset = Vector2.new(416, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/77"] = {
            Offset = Vector2.new(442, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/155"] = {
            Offset = Vector2.new(468, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/93"] = {
            Offset = Vector2.new(494, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/50"] = {
            Offset = Vector2.new(520, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/142"] = {
            Offset = Vector2.new(546, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/55"] = {
            Offset = Vector2.new(572, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/131"] = {
            Offset = Vector2.new(598, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/7"] = {
            Offset = Vector2.new(624, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/176"] = {
            Offset = Vector2.new(650, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/127"] = {
            Offset = Vector2.new(676, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/184"] = {
            Offset = Vector2.new(702, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/135"] = {
            Offset = Vector2.new(728, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/9"] = {
            Offset = Vector2.new(754, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/151"] = {
            Offset = Vector2.new(780, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/42"] = {
            Offset = Vector2.new(806, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/89"] = {
            Offset = Vector2.new(832, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/160"] = {
            Offset = Vector2.new(858, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/61"] = {
            Offset = Vector2.new(884, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/185"] = {
            Offset = Vector2.new(910, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/179"] = {
            Offset = Vector2.new(936, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/158"] = {
            Offset = Vector2.new(962, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/36"] = {
            Offset = Vector2.new(988, 78),
            Size = Vector2.new(26, 26)
        },
        ["smileys/48"] = {
            Offset = Vector2.new(0, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/102"] = {
            Offset = Vector2.new(26, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/95"] = {
            Offset = Vector2.new(52, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/51"] = {
            Offset = Vector2.new(78, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/150"] = {
            Offset = Vector2.new(104, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/4"] = {
            Offset = Vector2.new(130, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/153"] = {
            Offset = Vector2.new(156, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/23"] = {
            Offset = Vector2.new(182, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/71"] = {
            Offset = Vector2.new(208, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/114"] = {
            Offset = Vector2.new(234, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/16"] = {
            Offset = Vector2.new(260, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/65"] = {
            Offset = Vector2.new(286, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/1"] = {
            Offset = Vector2.new(312, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/178"] = {
            Offset = Vector2.new(338, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/146"] = {
            Offset = Vector2.new(364, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/49"] = {
            Offset = Vector2.new(390, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/118"] = {
            Offset = Vector2.new(416, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/20"] = {
            Offset = Vector2.new(442, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/35"] = {
            Offset = Vector2.new(468, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/174"] = {
            Offset = Vector2.new(494, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/108"] = {
            Offset = Vector2.new(520, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/99"] = {
            Offset = Vector2.new(546, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/117"] = {
            Offset = Vector2.new(572, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/0"] = {
            Offset = Vector2.new(598, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/30"] = {
            Offset = Vector2.new(624, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/73"] = {
            Offset = Vector2.new(650, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/170"] = {
            Offset = Vector2.new(676, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/112"] = {
            Offset = Vector2.new(702, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/45"] = {
            Offset = Vector2.new(728, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/40"] = {
            Offset = Vector2.new(754, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/41"] = {
            Offset = Vector2.new(780, 104),
            Size = Vector2.new(26, 26)
        },
        ["smileys/137"] = {
            Offset = Vector2.new(806, 104),
            Size = Vector2.new(26, 26)
        },
        ["blocks/mine/0"] = {
            Offset = Vector2.new(832, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2014/1"] = {
            Offset = Vector2.new(848, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2014/0"] = {
            Offset = Vector2.new(864, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/winter2018/3"] = {
            Offset = Vector2.new(880, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/winter2018/2"] = {
            Offset = Vector2.new(896, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/winter2018/1"] = {
            Offset = Vector2.new(912, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/winter2018/0"] = {
            Offset = Vector2.new(928, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/3"] = {
            Offset = Vector2.new(944, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/6"] = {
            Offset = Vector2.new(960, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/5"] = {
            Offset = Vector2.new(976, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/2"] = {
            Offset = Vector2.new(992, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/7"] = {
            Offset = Vector2.new(1008, 104),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/4"] = {
            Offset = Vector2.new(0, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/1"] = {
            Offset = Vector2.new(16, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/magic/0"] = {
            Offset = Vector2.new(32, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/3"] = {
            Offset = Vector2.new(48, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/6"] = {
            Offset = Vector2.new(64, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/5"] = {
            Offset = Vector2.new(80, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/2"] = {
            Offset = Vector2.new(96, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/7"] = {
            Offset = Vector2.new(112, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/4"] = {
            Offset = Vector2.new(128, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/1"] = {
            Offset = Vector2.new(144, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/plastic/0"] = {
            Offset = Vector2.new(160, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/gold/3"] = {
            Offset = Vector2.new(176, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/gold/2"] = {
            Offset = Vector2.new(192, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/gold/4"] = {
            Offset = Vector2.new(208, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/gold/1"] = {
            Offset = Vector2.new(224, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/gold/0"] = {
            Offset = Vector2.new(240, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/3"] = {
            Offset = Vector2.new(256, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/5"] = {
            Offset = Vector2.new(272, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/2"] = {
            Offset = Vector2.new(288, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/4"] = {
            Offset = Vector2.new(304, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/1"] = {
            Offset = Vector2.new(320, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/garden/0"] = {
            Offset = Vector2.new(336, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/spring2016/1"] = {
            Offset = Vector2.new(352, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/spring2016/0"] = {
            Offset = Vector2.new(368, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/3"] = {
            Offset = Vector2.new(384, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/5"] = {
            Offset = Vector2.new(400, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/2"] = {
            Offset = Vector2.new(416, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/4"] = {
            Offset = Vector2.new(432, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/1"] = {
            Offset = Vector2.new(448, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pipes/0"] = {
            Offset = Vector2.new(464, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/environment/3"] = {
            Offset = Vector2.new(480, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/environment/2"] = {
            Offset = Vector2.new(496, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/environment/4"] = {
            Offset = Vector2.new(512, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/environment/1"] = {
            Offset = Vector2.new(528, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/environment/0"] = {
            Offset = Vector2.new(544, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2016/3"] = {
            Offset = Vector2.new(560, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2016/2"] = {
            Offset = Vector2.new(576, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2016/4"] = {
            Offset = Vector2.new(592, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2016/1"] = {
            Offset = Vector2.new(608, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2016/0"] = {
            Offset = Vector2.new(624, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/3"] = {
            Offset = Vector2.new(640, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/5"] = {
            Offset = Vector2.new(656, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/2"] = {
            Offset = Vector2.new(672, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/4"] = {
            Offset = Vector2.new(688, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/1"] = {
            Offset = Vector2.new(704, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/outerspace/0"] = {
            Offset = Vector2.new(720, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/arctic/3"] = {
            Offset = Vector2.new(736, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/arctic/2"] = {
            Offset = Vector2.new(752, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/arctic/4"] = {
            Offset = Vector2.new(768, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/arctic/1"] = {
            Offset = Vector2.new(784, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/arctic/0"] = {
            Offset = Vector2.new(800, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/desert/3"] = {
            Offset = Vector2.new(816, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/desert/2"] = {
            Offset = Vector2.new(832, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/desert/4"] = {
            Offset = Vector2.new(848, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/desert/1"] = {
            Offset = Vector2.new(864, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/desert/0"] = {
            Offset = Vector2.new(880, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2011/1"] = {
            Offset = Vector2.new(896, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2011/0"] = {
            Offset = Vector2.new(912, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/generic/3"] = {
            Offset = Vector2.new(928, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/generic/2"] = {
            Offset = Vector2.new(944, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/generic/4"] = {
            Offset = Vector2.new(960, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/generic/1"] = {
            Offset = Vector2.new(976, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/generic/0"] = {
            Offset = Vector2.new(992, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/3"] = {
            Offset = Vector2.new(1008, 130),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/6"] = {
            Offset = Vector2.new(0, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/5"] = {
            Offset = Vector2.new(16, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/2"] = {
            Offset = Vector2.new(32, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/4"] = {
            Offset = Vector2.new(48, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/1"] = {
            Offset = Vector2.new(64, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/minerals/0"] = {
            Offset = Vector2.new(80, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/3"] = {
            Offset = Vector2.new(96, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/5"] = {
            Offset = Vector2.new(112, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/2"] = {
            Offset = Vector2.new(128, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/4"] = {
            Offset = Vector2.new(144, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/1"] = {
            Offset = Vector2.new(160, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/domestic/0"] = {
            Offset = Vector2.new(176, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2011/3"] = {
            Offset = Vector2.new(192, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2011/2"] = {
            Offset = Vector2.new(208, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2011/4"] = {
            Offset = Vector2.new(224, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2011/1"] = {
            Offset = Vector2.new(240, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/christmas2011/0"] = {
            Offset = Vector2.new(256, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dojo/1"] = {
            Offset = Vector2.new(272, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dojo/0"] = {
            Offset = Vector2.new(288, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2011/0"] = {
            Offset = Vector2.new(304, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/3"] = {
            Offset = Vector2.new(320, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/6"] = {
            Offset = Vector2.new(336, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/5"] = {
            Offset = Vector2.new(352, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/8"] = {
            Offset = Vector2.new(368, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/2"] = {
            Offset = Vector2.new(384, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/7"] = {
            Offset = Vector2.new(400, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/9"] = {
            Offset = Vector2.new(416, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/4"] = {
            Offset = Vector2.new(432, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/1"] = {
            Offset = Vector2.new(448, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/tiles/0"] = {
            Offset = Vector2.new(464, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/3"] = {
            Offset = Vector2.new(480, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/6"] = {
            Offset = Vector2.new(496, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/5"] = {
            Offset = Vector2.new(512, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/8"] = {
            Offset = Vector2.new(528, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/2"] = {
            Offset = Vector2.new(544, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/7"] = {
            Offset = Vector2.new(560, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/9"] = {
            Offset = Vector2.new(576, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/4"] = {
            Offset = Vector2.new(592, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/1"] = {
            Offset = Vector2.new(608, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/basic/0"] = {
            Offset = Vector2.new(624, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/3"] = {
            Offset = Vector2.new(640, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/6"] = {
            Offset = Vector2.new(656, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/5"] = {
            Offset = Vector2.new(672, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/2"] = {
            Offset = Vector2.new(688, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/7"] = {
            Offset = Vector2.new(704, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/4"] = {
            Offset = Vector2.new(720, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/1"] = {
            Offset = Vector2.new(736, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/glass/0"] = {
            Offset = Vector2.new(752, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/10"] = {
            Offset = Vector2.new(768, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/14"] = {
            Offset = Vector2.new(784, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/13"] = {
            Offset = Vector2.new(800, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/11"] = {
            Offset = Vector2.new(816, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/3"] = {
            Offset = Vector2.new(832, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/6"] = {
            Offset = Vector2.new(848, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/5"] = {
            Offset = Vector2.new(864, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/12"] = {
            Offset = Vector2.new(880, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/8"] = {
            Offset = Vector2.new(896, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/2"] = {
            Offset = Vector2.new(912, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/7"] = {
            Offset = Vector2.new(928, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/9"] = {
            Offset = Vector2.new(944, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/4"] = {
            Offset = Vector2.new(960, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/1"] = {
            Offset = Vector2.new(976, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sci-fi/0"] = {
            Offset = Vector2.new(992, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/prison/0"] = {
            Offset = Vector2.new(1008, 146),
            Size = Vector2.new(16, 16)
        },
        ["blocks/factory/3"] = {
            Offset = Vector2.new(0, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/factory/2"] = {
            Offset = Vector2.new(16, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/factory/4"] = {
            Offset = Vector2.new(32, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/factory/1"] = {
            Offset = Vector2.new(48, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/factory/0"] = {
            Offset = Vector2.new(64, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2016/3"] = {
            Offset = Vector2.new(80, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2016/2"] = {
            Offset = Vector2.new(96, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2016/4"] = {
            Offset = Vector2.new(112, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2016/1"] = {
            Offset = Vector2.new(128, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/summer2016/0"] = {
            Offset = Vector2.new(144, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/stone/3"] = {
            Offset = Vector2.new(160, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/stone/2"] = {
            Offset = Vector2.new(176, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/stone/1"] = {
            Offset = Vector2.new(192, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/stone/0"] = {
            Offset = Vector2.new(208, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/grass/2"] = {
            Offset = Vector2.new(224, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/grass/1"] = {
            Offset = Vector2.new(240, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/grass/0"] = {
            Offset = Vector2.new(256, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/3"] = {
            Offset = Vector2.new(272, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/5"] = {
            Offset = Vector2.new(288, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/2"] = {
            Offset = Vector2.new(304, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/4"] = {
            Offset = Vector2.new(320, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/1"] = {
            Offset = Vector2.new(336, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/sand/0"] = {
            Offset = Vector2.new(352, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/3"] = {
            Offset = Vector2.new(368, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/5"] = {
            Offset = Vector2.new(384, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/2"] = {
            Offset = Vector2.new(400, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/4"] = {
            Offset = Vector2.new(416, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/1"] = {
            Offset = Vector2.new(432, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/wildwest/0"] = {
            Offset = Vector2.new(448, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pirate/2"] = {
            Offset = Vector2.new(464, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pirate/1"] = {
            Offset = Vector2.new(480, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/pirate/0"] = {
            Offset = Vector2.new(496, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/3"] = {
            Offset = Vector2.new(512, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/6"] = {
            Offset = Vector2.new(528, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/5"] = {
            Offset = Vector2.new(544, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/8"] = {
            Offset = Vector2.new(560, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/2"] = {
            Offset = Vector2.new(576, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/7"] = {
            Offset = Vector2.new(592, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/9"] = {
            Offset = Vector2.new(608, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/4"] = {
            Offset = Vector2.new(624, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/1"] = {
            Offset = Vector2.new(640, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/beta/0"] = {
            Offset = Vector2.new(656, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dungeon/3"] = {
            Offset = Vector2.new(672, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dungeon/2"] = {
            Offset = Vector2.new(688, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dungeon/1"] = {
            Offset = Vector2.new(704, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/dungeon/0"] = {
            Offset = Vector2.new(720, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/3"] = {
            Offset = Vector2.new(736, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/6"] = {
            Offset = Vector2.new(752, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/5"] = {
            Offset = Vector2.new(768, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/8"] = {
            Offset = Vector2.new(784, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/2"] = {
            Offset = Vector2.new(800, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/7"] = {
            Offset = Vector2.new(816, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/4"] = {
            Offset = Vector2.new(832, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/1"] = {
            Offset = Vector2.new(848, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/candy/0"] = {
            Offset = Vector2.new(864, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/fairytale/3"] = {
            Offset = Vector2.new(880, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/fairytale/2"] = {
            Offset = Vector2.new(896, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/fairytale/4"] = {
            Offset = Vector2.new(912, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/fairytale/1"] = {
            Offset = Vector2.new(928, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/fairytale/0"] = {
            Offset = Vector2.new(944, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/farm/0"] = {
            Offset = Vector2.new(960, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/10"] = {
            Offset = Vector2.new(976, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/11"] = {
            Offset = Vector2.new(992, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/3"] = {
            Offset = Vector2.new(1008, 162),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/6"] = {
            Offset = Vector2.new(0, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/5"] = {
            Offset = Vector2.new(16, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/12"] = {
            Offset = Vector2.new(32, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/8"] = {
            Offset = Vector2.new(48, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/2"] = {
            Offset = Vector2.new(64, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/7"] = {
            Offset = Vector2.new(80, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/9"] = {
            Offset = Vector2.new(96, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/4"] = {
            Offset = Vector2.new(112, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/1"] = {
            Offset = Vector2.new(128, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/industrial/0"] = {
            Offset = Vector2.new(144, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/medieval/3"] = {
            Offset = Vector2.new(160, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/medieval/2"] = {
            Offset = Vector2.new(176, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/medieval/4"] = {
            Offset = Vector2.new(192, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/medieval/1"] = {
            Offset = Vector2.new(208, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/medieval/0"] = {
            Offset = Vector2.new(224, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/marble/3"] = {
            Offset = Vector2.new(240, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/marble/2"] = {
            Offset = Vector2.new(256, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/marble/1"] = {
            Offset = Vector2.new(272, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/marble/0"] = {
            Offset = Vector2.new(288, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/3"] = {
            Offset = Vector2.new(304, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/6"] = {
            Offset = Vector2.new(320, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/5"] = {
            Offset = Vector2.new(336, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/8"] = {
            Offset = Vector2.new(352, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/2"] = {
            Offset = Vector2.new(368, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/7"] = {
            Offset = Vector2.new(384, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/9"] = {
            Offset = Vector2.new(400, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/4"] = {
            Offset = Vector2.new(416, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/1"] = {
            Offset = Vector2.new(432, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/brick/0"] = {
            Offset = Vector2.new(448, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/cloud/1"] = {
            Offset = Vector2.new(464, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/cloud/0"] = {
            Offset = Vector2.new(480, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/lava/2"] = {
            Offset = Vector2.new(496, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/lava/1"] = {
            Offset = Vector2.new(512, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/lava/0"] = {
            Offset = Vector2.new(528, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2015/3"] = {
            Offset = Vector2.new(544, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2015/2"] = {
            Offset = Vector2.new(560, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2015/1"] = {
            Offset = Vector2.new(576, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/halloween2015/0"] = {
            Offset = Vector2.new(592, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/metal/2"] = {
            Offset = Vector2.new(608, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/metal/1"] = {
            Offset = Vector2.new(624, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/metal/0"] = {
            Offset = Vector2.new(640, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/3"] = {
            Offset = Vector2.new(656, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/6"] = {
            Offset = Vector2.new(672, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/5"] = {
            Offset = Vector2.new(688, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/8"] = {
            Offset = Vector2.new(704, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/2"] = {
            Offset = Vector2.new(720, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/7"] = {
            Offset = Vector2.new(736, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/4"] = {
            Offset = Vector2.new(752, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/1"] = {
            Offset = Vector2.new(768, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/construction/0"] = {
            Offset = Vector2.new(784, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/3"] = {
            Offset = Vector2.new(800, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/6"] = {
            Offset = Vector2.new(816, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/5"] = {
            Offset = Vector2.new(832, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/2"] = {
            Offset = Vector2.new(848, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/4"] = {
            Offset = Vector2.new(864, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/1"] = {
            Offset = Vector2.new(880, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/jungle/0"] = {
            Offset = Vector2.new(896, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/secrets/3"] = {
            Offset = Vector2.new(912, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/secrets/2"] = {
            Offset = Vector2.new(928, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/secrets/1"] = {
            Offset = Vector2.new(944, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/secrets/0"] = {
            Offset = Vector2.new(960, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/3"] = {
            Offset = Vector2.new(976, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/6"] = {
            Offset = Vector2.new(992, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/5"] = {
            Offset = Vector2.new(1008, 178),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/8"] = {
            Offset = Vector2.new(0, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/2"] = {
            Offset = Vector2.new(16, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/7"] = {
            Offset = Vector2.new(32, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/9"] = {
            Offset = Vector2.new(48, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/4"] = {
            Offset = Vector2.new(64, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/1"] = {
            Offset = Vector2.new(80, 194),
            Size = Vector2.new(16, 16)
        },
        ["blocks/checker/0"] = {
            Offset = Vector2.new(96, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/mine/0"] = {
            Offset = Vector2.new(112, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/clay/3"] = {
            Offset = Vector2.new(128, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/clay/2"] = {
            Offset = Vector2.new(144, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/clay/4"] = {
            Offset = Vector2.new(160, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/clay/1"] = {
            Offset = Vector2.new(176, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/clay/0"] = {
            Offset = Vector2.new(192, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/gold/2"] = {
            Offset = Vector2.new(208, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/gold/1"] = {
            Offset = Vector2.new(224, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/gold/0"] = {
            Offset = Vector2.new(240, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/environment/3"] = {
            Offset = Vector2.new(256, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/environment/2"] = {
            Offset = Vector2.new(272, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/environment/4"] = {
            Offset = Vector2.new(288, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/environment/1"] = {
            Offset = Vector2.new(304, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/environment/0"] = {
            Offset = Vector2.new(320, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/autumn2014/2"] = {
            Offset = Vector2.new(336, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/autumn2014/1"] = {
            Offset = Vector2.new(352, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/autumn2014/0"] = {
            Offset = Vector2.new(368, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/10"] = {
            Offset = Vector2.new(384, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/3"] = {
            Offset = Vector2.new(400, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/6"] = {
            Offset = Vector2.new(416, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/5"] = {
            Offset = Vector2.new(432, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/8"] = {
            Offset = Vector2.new(448, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/2"] = {
            Offset = Vector2.new(464, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/7"] = {
            Offset = Vector2.new(480, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/9"] = {
            Offset = Vector2.new(496, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/4"] = {
            Offset = Vector2.new(512, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/1"] = {
            Offset = Vector2.new(528, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/cave/0"] = {
            Offset = Vector2.new(544, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/outerspace/3"] = {
            Offset = Vector2.new(560, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/outerspace/2"] = {
            Offset = Vector2.new(576, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/outerspace/1"] = {
            Offset = Vector2.new(592, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/outerspace/0"] = {
            Offset = Vector2.new(608, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/arctic/1"] = {
            Offset = Vector2.new(624, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/arctic/0"] = {
            Offset = Vector2.new(640, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/desert/2"] = {
            Offset = Vector2.new(656, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/desert/1"] = {
            Offset = Vector2.new(672, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/desert/0"] = {
            Offset = Vector2.new(688, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2011/3"] = {
            Offset = Vector2.new(704, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2011/2"] = {
            Offset = Vector2.new(720, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2011/1"] = {
            Offset = Vector2.new(736, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2011/0"] = {
            Offset = Vector2.new(752, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/3"] = {
            Offset = Vector2.new(768, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/5"] = {
            Offset = Vector2.new(784, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/2"] = {
            Offset = Vector2.new(800, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/4"] = {
            Offset = Vector2.new(816, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/1"] = {
            Offset = Vector2.new(832, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/neon/0"] = {
            Offset = Vector2.new(848, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/domestic/3"] = {
            Offset = Vector2.new(864, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/domestic/2"] = {
            Offset = Vector2.new(880, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/domestic/4"] = {
            Offset = Vector2.new(896, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/domestic/1"] = {
            Offset = Vector2.new(912, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/domestic/0"] = {
            Offset = Vector2.new(928, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/3"] = {
            Offset = Vector2.new(944, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/6"] = {
            Offset = Vector2.new(960, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/5"] = {
            Offset = Vector2.new(976, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/2"] = {
            Offset = Vector2.new(992, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/7"] = {
            Offset = Vector2.new(1008, 194),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/4"] = {
            Offset = Vector2.new(0, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/1"] = {
            Offset = Vector2.new(16, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/dojo/0"] = {
            Offset = Vector2.new(32, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/3"] = {
            Offset = Vector2.new(48, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/6"] = {
            Offset = Vector2.new(64, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/5"] = {
            Offset = Vector2.new(80, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/2"] = {
            Offset = Vector2.new(96, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/7"] = {
            Offset = Vector2.new(112, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/4"] = {
            Offset = Vector2.new(128, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/1"] = {
            Offset = Vector2.new(144, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/pastel/0"] = {
            Offset = Vector2.new(160, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/3"] = {
            Offset = Vector2.new(176, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/6"] = {
            Offset = Vector2.new(192, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/5"] = {
            Offset = Vector2.new(208, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/2"] = {
            Offset = Vector2.new(224, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/7"] = {
            Offset = Vector2.new(240, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/4"] = {
            Offset = Vector2.new(256, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/1"] = {
            Offset = Vector2.new(272, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/carnival/0"] = {
            Offset = Vector2.new(288, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/3"] = {
            Offset = Vector2.new(304, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/6"] = {
            Offset = Vector2.new(320, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/5"] = {
            Offset = Vector2.new(336, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/8"] = {
            Offset = Vector2.new(352, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/2"] = {
            Offset = Vector2.new(368, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/7"] = {
            Offset = Vector2.new(384, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/4"] = {
            Offset = Vector2.new(400, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/1"] = {
            Offset = Vector2.new(416, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/canvas/0"] = {
            Offset = Vector2.new(432, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/3"] = {
            Offset = Vector2.new(448, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/6"] = {
            Offset = Vector2.new(464, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/5"] = {
            Offset = Vector2.new(480, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/8"] = {
            Offset = Vector2.new(496, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/2"] = {
            Offset = Vector2.new(512, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/7"] = {
            Offset = Vector2.new(528, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/9"] = {
            Offset = Vector2.new(544, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/4"] = {
            Offset = Vector2.new(560, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/1"] = {
            Offset = Vector2.new(576, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/basic/0"] = {
            Offset = Vector2.new(592, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sci-fi/0"] = {
            Offset = Vector2.new(608, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/prison/3"] = {
            Offset = Vector2.new(624, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/prison/2"] = {
            Offset = Vector2.new(640, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/prison/1"] = {
            Offset = Vector2.new(656, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/prison/0"] = {
            Offset = Vector2.new(672, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/summer2016/3"] = {
            Offset = Vector2.new(688, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/summer2016/2"] = {
            Offset = Vector2.new(704, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/summer2016/1"] = {
            Offset = Vector2.new(720, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/summer2016/0"] = {
            Offset = Vector2.new(736, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/3"] = {
            Offset = Vector2.new(752, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/6"] = {
            Offset = Vector2.new(768, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/5"] = {
            Offset = Vector2.new(784, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/2"] = {
            Offset = Vector2.new(800, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/7"] = {
            Offset = Vector2.new(816, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/4"] = {
            Offset = Vector2.new(832, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/1"] = {
            Offset = Vector2.new(848, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/stone/0"] = {
            Offset = Vector2.new(864, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/3"] = {
            Offset = Vector2.new(880, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/5"] = {
            Offset = Vector2.new(896, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/2"] = {
            Offset = Vector2.new(912, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/4"] = {
            Offset = Vector2.new(928, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/1"] = {
            Offset = Vector2.new(944, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/sand/0"] = {
            Offset = Vector2.new(960, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/3"] = {
            Offset = Vector2.new(976, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/5"] = {
            Offset = Vector2.new(992, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/2"] = {
            Offset = Vector2.new(1008, 210),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/4"] = {
            Offset = Vector2.new(0, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/1"] = {
            Offset = Vector2.new(16, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/wildwest/0"] = {
            Offset = Vector2.new(32, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/swamp/1"] = {
            Offset = Vector2.new(48, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/swamp/0"] = {
            Offset = Vector2.new(64, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/pirate/3"] = {
            Offset = Vector2.new(80, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/pirate/2"] = {
            Offset = Vector2.new(96, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/pirate/1"] = {
            Offset = Vector2.new(112, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/pirate/0"] = {
            Offset = Vector2.new(128, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/3"] = {
            Offset = Vector2.new(144, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/6"] = {
            Offset = Vector2.new(160, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/5"] = {
            Offset = Vector2.new(176, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/8"] = {
            Offset = Vector2.new(192, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/2"] = {
            Offset = Vector2.new(208, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/7"] = {
            Offset = Vector2.new(224, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/9"] = {
            Offset = Vector2.new(240, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/4"] = {
            Offset = Vector2.new(256, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/1"] = {
            Offset = Vector2.new(272, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/beta/0"] = {
            Offset = Vector2.new(288, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/candy/1"] = {
            Offset = Vector2.new(304, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/candy/0"] = {
            Offset = Vector2.new(320, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/fairytale/3"] = {
            Offset = Vector2.new(336, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/fairytale/2"] = {
            Offset = Vector2.new(352, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/fairytale/1"] = {
            Offset = Vector2.new(368, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/fairytale/0"] = {
            Offset = Vector2.new(384, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/industrial/3"] = {
            Offset = Vector2.new(400, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/industrial/2"] = {
            Offset = Vector2.new(416, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/industrial/4"] = {
            Offset = Vector2.new(432, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/industrial/1"] = {
            Offset = Vector2.new(448, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/industrial/0"] = {
            Offset = Vector2.new(464, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/3"] = {
            Offset = Vector2.new(480, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/5"] = {
            Offset = Vector2.new(496, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/2"] = {
            Offset = Vector2.new(512, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/4"] = {
            Offset = Vector2.new(528, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/1"] = {
            Offset = Vector2.new(544, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/monster/0"] = {
            Offset = Vector2.new(560, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/3"] = {
            Offset = Vector2.new(576, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/6"] = {
            Offset = Vector2.new(592, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/5"] = {
            Offset = Vector2.new(608, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/2"] = {
            Offset = Vector2.new(624, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/4"] = {
            Offset = Vector2.new(640, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/1"] = {
            Offset = Vector2.new(656, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/medieval/0"] = {
            Offset = Vector2.new(672, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/marble/2"] = {
            Offset = Vector2.new(688, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/marble/1"] = {
            Offset = Vector2.new(704, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/marble/0"] = {
            Offset = Vector2.new(720, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/3"] = {
            Offset = Vector2.new(736, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/6"] = {
            Offset = Vector2.new(752, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/5"] = {
            Offset = Vector2.new(768, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/8"] = {
            Offset = Vector2.new(784, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/2"] = {
            Offset = Vector2.new(800, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/7"] = {
            Offset = Vector2.new(816, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/9"] = {
            Offset = Vector2.new(832, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/4"] = {
            Offset = Vector2.new(848, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/1"] = {
            Offset = Vector2.new(864, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/brick/0"] = {
            Offset = Vector2.new(880, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/lava/2"] = {
            Offset = Vector2.new(896, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/lava/1"] = {
            Offset = Vector2.new(912, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/lava/0"] = {
            Offset = Vector2.new(928, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/christmas2012/2"] = {
            Offset = Vector2.new(944, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/christmas2012/1"] = {
            Offset = Vector2.new(960, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/christmas2012/0"] = {
            Offset = Vector2.new(976, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2015/2"] = {
            Offset = Vector2.new(992, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2015/1"] = {
            Offset = Vector2.new(1008, 226),
            Size = Vector2.new(16, 16)
        },
        ["background/halloween2015/0"] = {
            Offset = Vector2.new(0, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/3"] = {
            Offset = Vector2.new(16, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/6"] = {
            Offset = Vector2.new(32, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/5"] = {
            Offset = Vector2.new(48, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/8"] = {
            Offset = Vector2.new(64, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/2"] = {
            Offset = Vector2.new(80, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/7"] = {
            Offset = Vector2.new(96, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/9"] = {
            Offset = Vector2.new(112, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/4"] = {
            Offset = Vector2.new(128, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/1"] = {
            Offset = Vector2.new(144, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/normal/0"] = {
            Offset = Vector2.new(160, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/3"] = {
            Offset = Vector2.new(176, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/6"] = {
            Offset = Vector2.new(192, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/5"] = {
            Offset = Vector2.new(208, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/2"] = {
            Offset = Vector2.new(224, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/4"] = {
            Offset = Vector2.new(240, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/1"] = {
            Offset = Vector2.new(256, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/jungle/0"] = {
            Offset = Vector2.new(272, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/3"] = {
            Offset = Vector2.new(288, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/6"] = {
            Offset = Vector2.new(304, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/5"] = {
            Offset = Vector2.new(320, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/8"] = {
            Offset = Vector2.new(336, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/2"] = {
            Offset = Vector2.new(352, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/7"] = {
            Offset = Vector2.new(368, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/9"] = {
            Offset = Vector2.new(384, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/4"] = {
            Offset = Vector2.new(400, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/1"] = {
            Offset = Vector2.new(416, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/checker/0"] = {
            Offset = Vector2.new(432, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/water/3"] = {
            Offset = Vector2.new(448, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/water/2"] = {
            Offset = Vector2.new(464, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/water/4"] = {
            Offset = Vector2.new(480, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/water/1"] = {
            Offset = Vector2.new(496, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/water/0"] = {
            Offset = Vector2.new(512, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/3"] = {
            Offset = Vector2.new(528, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/6"] = {
            Offset = Vector2.new(544, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/5"] = {
            Offset = Vector2.new(560, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/8"] = {
            Offset = Vector2.new(576, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/2"] = {
            Offset = Vector2.new(592, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/7"] = {
            Offset = Vector2.new(608, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/9"] = {
            Offset = Vector2.new(624, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/4"] = {
            Offset = Vector2.new(640, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/1"] = {
            Offset = Vector2.new(656, 242),
            Size = Vector2.new(16, 16)
        },
        ["background/dark/0"] = {
            Offset = Vector2.new(672, 242),
            Size = Vector2.new(16, 16)
        },
    }
}

return SpriteData
